apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: speer
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: speer
    spec:
      containers:
      - name: master
        image: gcr.io/speer-slack-bot-001/speer:latest
